version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:12.18.3

jobs:
  install_dependencies:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            - dependency-cache-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: '.'
          paths:
            - node_modules

  test:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - run:
          name: Run local rules tests
          command: npm run test

  tag_and_release:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: '.'
      - run:
          name: Tag, build and publish package
          command: npm run semantic-release

workflows:
  build-and-release:
    jobs:
      - install_dependencies:
          name: install_dependencies
          context: GLOBAL_ORG
          filters:
            branches:
              only:
                - master

      - test:
          name: test
          context: GLOBAL_ORG

      - tag_and_release:
          name: tag_and_release
          context: GLOBAL_ORG
          requires:
            - install_dependencies
          filters:
            branches:
              only:
                - master
